
allChars = """Agrave	0x00C0	À	LATIN CAPITAL LETTER A WITH GRAVE	GF-latin-core	0
Aacute	0x00C1	Á	LATIN CAPITAL LETTER A WITH ACUTE	GF-latin-core	0
Acircumflex	0x00C2	Â	LATIN CAPITAL LETTER A WITH CIRCUMFLEX	GF-latin-core	0
Atilde	0x00C3	Ã	LATIN CAPITAL LETTER A WITH TILDE	GF-latin-core	0
Adieresis	0x00C4	Ä	LATIN CAPITAL LETTER A WITH DIAERESIS	GF-latin-core	0
Aring	0x00C5	Å	LATIN CAPITAL LETTER A WITH RING ABOVE	GF-latin-core	0
Aringacute	0x01FA	Ǻ	LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE	GF-latin-plus	0
Agravedbl	0x0200	Ȁ	LATIN CAPITAL LETTER A WITH DOUBLE GRAVE	GF-latin-plus	0
Ainvertedbreve	0x0202	Ȃ	LATIN CAPITAL LETTER A WITH INVERTED BREVE	GF-latin-plus	0
Amacron	0x0100	Ā	LATIN CAPITAL LETTER A WITH MACRON	GF-latin-plus	0
Abreve	0x0102	Ă	LATIN CAPITAL LETTER A WITH BREVE	GF-latin-plus	0
Aogonek	0x0104	Ą	LATIN CAPITAL LETTER A WITH OGONEK	GF-latin-plus	0
AE	0x00C6	Æ	LATIN CAPITAL LETTER AE	GF-latin-core	0
AEacute	0x01FC	Ǽ	LATIN CAPITAL LETTER AE WITH ACUTE	GF-latin-plus	0
Ccedilla	0x00C7	Ç	LATIN CAPITAL LETTER C WITH CEDILLA	GF-latin-core	0
Cacute	0x0106	Ć	LATIN CAPITAL LETTER C WITH ACUTE	GF-latin-plus	0
Ccircumflex	0x0108	Ĉ	LATIN CAPITAL LETTER C WITH CIRCUMFLEX	GF-latin-plus	0
Cdotaccent	0x010A	Ċ	LATIN CAPITAL LETTER C WITH DOT ABOVE	GF-latin-plus	0
Ccaron	0x010C	Č	LATIN CAPITAL LETTER C WITH CARON	GF-latin-plus	0
Dcaron	0x010E	Ď	LATIN CAPITAL LETTER D WITH CARON	GF-latin-plus	0
Dcroat	0x0110	Đ	LATIN CAPITAL LETTER D WITH STROKE	GF-latin-plus	0
Eth	0x00D0	Ð	LATIN CAPITAL LETTER ETH	GF-latin-core	0
Egrave	0x00C8	È	LATIN CAPITAL LETTER E WITH GRAVE	GF-latin-core	0
Eacute	0x00C9	É	LATIN CAPITAL LETTER E WITH ACUTE	GF-latin-core	0
Ecircumflex	0x00CA	Ê	LATIN CAPITAL LETTER E WITH CIRCUMFLEX	GF-latin-core	0
Edieresis	0x00CB	Ë	LATIN CAPITAL LETTER E WITH DIAERESIS	GF-latin-core	0
Egravedbl	0x0204	Ȅ	LATIN CAPITAL LETTER E WITH DOUBLE GRAVE	GF-latin-plus	0
Einvertedbreve	0x0206	Ȇ	LATIN CAPITAL LETTER E WITH INVERTED BREVE	GF-latin-plus	0
Emacron	0x0112	Ē	LATIN CAPITAL LETTER E WITH MACRON	GF-latin-plus	0
Ebreve	0x0114	Ĕ	LATIN CAPITAL LETTER E WITH BREVE	GF-latin-plus	0
Edotaccent	0x0116	Ė	LATIN CAPITAL LETTER E WITH DOT ABOVE	GF-latin-plus	0
Eogonek	0x0118	Ę	LATIN CAPITAL LETTER E WITH OGONEK	GF-latin-plus	0
Ecaron	0x011A	Ě	LATIN CAPITAL LETTER E WITH CARON	GF-latin-plus	0
Gcircumflex	0x011C	Ĝ	LATIN CAPITAL LETTER G WITH CIRCUMFLEX	GF-latin-plus	0
Gbreve	0x011E	Ğ	LATIN CAPITAL LETTER G WITH BREVE	GF-latin-plus	0
Gdotaccent	0x0120	Ġ	LATIN CAPITAL LETTER G WITH DOT ABOVE	GF-latin-plus	0
Gcedilla	0x0122	Ģ	LATIN CAPITAL LETTER G WITH CEDILLA	GF-latin-plus	0
Hcircumflex	0x0124	Ĥ	LATIN CAPITAL LETTER H WITH CIRCUMFLEX	GF-latin-plus	0
Hbar	0x0126	Ħ	LATIN CAPITAL LETTER H WITH STROKE	GF-latin-plus	0
Igrave	0x00CC	Ì	LATIN CAPITAL LETTER I WITH GRAVE	GF-latin-core	0
Iacute	0x00CD	Í	LATIN CAPITAL LETTER I WITH ACUTE	GF-latin-core	0
Icircumflex	0x00CE	Î	LATIN CAPITAL LETTER I WITH CIRCUMFLEX	GF-latin-core	0
Idieresis	0x00CF	Ï	LATIN CAPITAL LETTER I WITH DIAERESIS	GF-latin-core	0
Igravedbl	0x0208	Ȉ	LATIN CAPITAL LETTER I WITH DOUBLE GRAVE	GF-latin-plus	0
Iinvertedbreve	0x020A	Ȋ	LATIN CAPITAL LETTER I WITH INVERTED BREVE	GF-latin-plus	0
Itilde	0x0128	Ĩ	LATIN CAPITAL LETTER I WITH TILDE	GF-latin-plus	0
Imacron	0x012A	Ī	LATIN CAPITAL LETTER I WITH MACRON	GF-latin-plus	0
Ibreve	0x012C	Ĭ	LATIN CAPITAL LETTER I WITH BREVE	GF-latin-plus	0
Iogonek	0x012E	Į	LATIN CAPITAL LETTER I WITH OGONEK	GF-latin-plus	0
Idotaccent	0x0130	İ	LATIN CAPITAL LETTER I WITH DOT ABOVE	GF-latin-plus	0
Lacute	0x0139	Ĺ	LATIN CAPITAL LETTER L WITH ACUTE	GF-latin-plus	0
Lcedilla	0x013B	Ļ	LATIN CAPITAL LETTER L WITH CEDILLA	GF-latin-plus	0
Lcaron	0x013D	Ľ	LATIN CAPITAL LETTER L WITH CARON	GF-latin-plus	0
Ldot	0x013F	Ŀ	LATIN CAPITAL LETTER L WITH MIDDLE DOT	GF-latin-plus	0
Lslash	0x0141	Ł	LATIN CAPITAL LETTER L WITH STROKE	GF-latin-plus	0
Ntilde	0x00D1	Ñ	LATIN CAPITAL LETTER N WITH TILDE	GF-latin-core	0
Nacute	0x0143	Ń	LATIN CAPITAL LETTER N WITH ACUTE	GF-latin-plus	0
Ncedilla	0x0145	Ņ	LATIN CAPITAL LETTER N WITH CEDILLA	GF-latin-plus	0
Ncaron	0x0147	Ň	LATIN CAPITAL LETTER N WITH CARON	GF-latin-plus	0
Eng	0x014A	Ŋ	LATIN CAPITAL LETTER ENG	GF-latin-plus	0
Ograve	0x00D2	Ò	LATIN CAPITAL LETTER O WITH GRAVE	GF-latin-core	0
Oacute	0x00D3	Ó	LATIN CAPITAL LETTER O WITH ACUTE	GF-latin-core	0
Ocircumflex	0x00D4	Ô	LATIN CAPITAL LETTER O WITH CIRCUMFLEX	GF-latin-core	0
Otilde	0x00D5	Õ	LATIN CAPITAL LETTER O WITH TILDE	GF-latin-core	0
Odieresis	0x00D6	Ö	LATIN CAPITAL LETTER O WITH DIAERESIS	GF-latin-core	0
Oslash	0x00D8	Ø	LATIN CAPITAL LETTER O WITH STROKE	GF-latin-core	0
Oslashacute	0x01FE	Ǿ	LATIN CAPITAL LETTER O WITH STROKE AND ACUTE	GF-latin-plus	0
Ogravedbl	0x020C	Ȍ	LATIN CAPITAL LETTER O WITH DOUBLE GRAVE	GF-latin-plus	0
Oinvertedbreve	0x020E	Ȏ	LATIN CAPITAL LETTER O WITH INVERTED BREVE	GF-latin-plus	0
Odieresismacron	0x022A	Ȫ	LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON	GF-latin-plus	0
Otildemacron	0x022C	Ȭ	LATIN CAPITAL LETTER O WITH TILDE AND MACRON	GF-latin-plus	0
Odotmacron	0x0230	Ȱ	LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON	GF-latin-plus	0
Oogonek	0x01EA	Ǫ	LATIN CAPITAL LETTER O WITH OGONEK	GF-latin-plus	0
Omacron	0x014C	Ō	LATIN CAPITAL LETTER O WITH MACRON	GF-latin-plus	0
Obreve	0x014E	Ŏ	LATIN CAPITAL LETTER O WITH BREVE	GF-latin-plus	0
Ohungarumlaut	0x0150	Ő	LATIN CAPITAL LETTER O WITH DOUBLE ACUTE	GF-latin-plus	0
OE	0x0152	Œ	LATIN CAPITAL LIGATURE OE	GF-latin-core	0
Ohorn	0x01A0	Ơ	LATIN CAPITAL LETTER O WITH HORN	GF-latin-plus	0
Racute	0x0154	Ŕ	LATIN CAPITAL LETTER R WITH ACUTE	GF-latin-plus	0
Rcedilla	0x0156	Ŗ	LATIN CAPITAL LETTER R WITH CEDILLA	GF-latin-plus	0
Rcaron	0x0158	Ř	LATIN CAPITAL LETTER R WITH CARON	GF-latin-plus	0
Rgravedbl	0x0210	Ȑ	LATIN CAPITAL LETTER R WITH DOUBLE GRAVE	GF-latin-plus	0
Rinvertedbreve	0x0212	Ȓ	LATIN CAPITAL LETTER R WITH INVERTED BREVE	GF-latin-plus	0
Scommaaccent	0x0218	Ș	LATIN CAPITAL LETTER S WITH COMMA BELOW	GF-latin-plus	0
Sacute	0x015A	Ś	LATIN CAPITAL LETTER S WITH ACUTE	GF-latin-plus	0
Scircumflex	0x015C	Ŝ	LATIN CAPITAL LETTER S WITH CIRCUMFLEX	GF-latin-plus	0
Scedilla	0x015E	Ş	LATIN CAPITAL LETTER S WITH CEDILLA	GF-latin-plus	0
Scaron	0x0160	Š	LATIN CAPITAL LETTER S WITH CARON	GF-latin-plus	0
Tcommaaccent	0x021A	Ț	LATIN CAPITAL LETTER T WITH COMMA BELOW	GF-latin-plus	0
Tcedilla	0x0162	Ţ	LATIN CAPITAL LETTER T WITH CEDILLA	GF-latin-plus	0
Tcaron	0x0164	Ť	LATIN CAPITAL LETTER T WITH CARON	GF-latin-plus	0
Tbar	0x0166	Ŧ	LATIN CAPITAL LETTER T WITH STROKE	GF-latin-plus	0
Ugrave	0x00D9	Ù	LATIN CAPITAL LETTER U WITH GRAVE	GF-latin-core	0
Uacute	0x00DA	Ú	LATIN CAPITAL LETTER U WITH ACUTE	GF-latin-core	0
Ucircumflex	0x00DB	Û	LATIN CAPITAL LETTER U WITH CIRCUMFLEX	GF-latin-core	0
Udieresis	0x00DC	Ü	LATIN CAPITAL LETTER U WITH DIAERESIS	GF-latin-core	0
Ugravedbl	0x0214	Ȕ	LATIN CAPITAL LETTER U WITH DOUBLE GRAVE	GF-latin-plus	0
Uinvertedbreve	0x0216	Ȗ	LATIN CAPITAL LETTER U WITH INVERTED BREVE	GF-latin-plus	0
Utilde	0x0168	Ũ	LATIN CAPITAL LETTER U WITH TILDE	GF-latin-plus	0
Umacron	0x016A	Ū	LATIN CAPITAL LETTER U WITH MACRON	GF-latin-plus	0
Ubreve	0x016C	Ŭ	LATIN CAPITAL LETTER U WITH BREVE	GF-latin-plus	0
Uring	0x016E	Ů	LATIN CAPITAL LETTER U WITH RING ABOVE	GF-latin-plus	0
Uhungarumlaut	0x0170	Ű	LATIN CAPITAL LETTER U WITH DOUBLE ACUTE	GF-latin-plus	0
Uogonek	0x0172	Ų	LATIN CAPITAL LETTER U WITH OGONEK	GF-latin-plus	0
Uhorn	0x01AF	Ư	LATIN CAPITAL LETTER U WITH HORN	GF-latin-plus	0
Wcircumflex	0x0174	Ŵ	LATIN CAPITAL LETTER W WITH CIRCUMFLEX	GF-latin-plus	0
Yacute	0x00DD	Ý	LATIN CAPITAL LETTER Y WITH ACUTE	GF-latin-core	0
Ydieresis	0x0178	Ÿ	LATIN CAPITAL LETTER Y WITH DIAERESIS	GF-latin-plus	0
Ymacron	0x0232	Ȳ	LATIN CAPITAL LETTER Y WITH MACRON	GF-latin-plus	0
Ycircumflex	0x0176	Ŷ	LATIN CAPITAL LETTER Y WITH CIRCUMFLEX	GF-latin-plus	0
Thorn	0x00DE	Þ	LATIN CAPITAL LETTER THORN	GF-latin-core	0
Zacute	0x0179	Ź	LATIN CAPITAL LETTER Z WITH ACUTE	GF-latin-plus	0
Zdotaccent	0x017B	Ż	LATIN CAPITAL LETTER Z WITH DOT ABOVE	GF-latin-plus	0
Zcaron	0x017D	Ž	LATIN CAPITAL LETTER Z WITH CARON	GF-latin-plus	0
Schwa	0x018F	Ə	LATIN CAPITAL LETTER SCHWA	GF-latin-plus	0
germandbls	0x00DF	ß	LATIN SMALL LETTER SHARP S	GF-latin-core	0
agrave	0x00E0	à	LATIN SMALL LETTER A WITH GRAVE	GF-latin-core	0
aacute	0x00E1	á	LATIN SMALL LETTER A WITH ACUTE	GF-latin-core	0
acircumflex	0x00E2	â	LATIN SMALL LETTER A WITH CIRCUMFLEX	GF-latin-core	0
atilde	0x00E3	ã	LATIN SMALL LETTER A WITH TILDE	GF-latin-core	0
adieresis	0x00E4	ä	LATIN SMALL LETTER A WITH DIAERESIS	GF-latin-core	0
aring	0x00E5	å	LATIN SMALL LETTER A WITH RING ABOVE	GF-latin-core	0
aringacute	0x01FB	ǻ	LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE	GF-latin-plus	0
amacron	0x0101	ā	LATIN SMALL LETTER A WITH MACRON	GF-latin-plus	0
abreve	0x0103	ă	LATIN SMALL LETTER A WITH BREVE	GF-latin-plus	0
aogonek	0x0105	ą	LATIN SMALL LETTER A WITH OGONEK	GF-latin-plus	0
ae	0x00E6	æ	LATIN SMALL LETTER AE	GF-latin-core	0
aeacute	0x01FD	ǽ	LATIN SMALL LETTER AE WITH ACUTE	GF-latin-plus	0
ccedilla	0x00E7	ç	LATIN SMALL LETTER C WITH CEDILLA	GF-latin-core	0
cacute	0x0107	ć	LATIN SMALL LETTER C WITH ACUTE	GF-latin-plus	0
ccircumflex	0x0109	ĉ	LATIN SMALL LETTER C WITH CIRCUMFLEX	GF-latin-plus	0
cdotaccent	0x010B	ċ	LATIN SMALL LETTER C WITH DOT ABOVE	GF-latin-plus	0
ccaron	0x010D	č	LATIN SMALL LETTER C WITH CARON	GF-latin-plus	0
dcaron	0x010F	ď	LATIN SMALL LETTER D WITH CARON	GF-latin-plus	0
dcroat	0x0111	đ	LATIN SMALL LETTER D WITH STROKE	GF-latin-plus	0
eth	0x00F0	ð	LATIN SMALL LETTER ETH	GF-latin-core	0
egrave	0x00E8	è	LATIN SMALL LETTER E WITH GRAVE	GF-latin-core	0
eacute	0x00E9	é	LATIN SMALL LETTER E WITH ACUTE	GF-latin-core	0
ecircumflex	0x00EA	ê	LATIN SMALL LETTER E WITH CIRCUMFLEX	GF-latin-core	0
edieresis	0x00EB	ë	LATIN SMALL LETTER E WITH DIAERESIS	GF-latin-core	0
emacron	0x0113	ē	LATIN SMALL LETTER E WITH MACRON	GF-latin-plus	0
ebreve	0x0115	ĕ	LATIN SMALL LETTER E WITH BREVE	GF-latin-plus	0
edotaccent	0x0117	ė	LATIN SMALL LETTER E WITH DOT ABOVE	GF-latin-plus	0
eogonek	0x0119	ę	LATIN SMALL LETTER E WITH OGONEK	GF-latin-plus	0
ecaron	0x011B	ě	LATIN SMALL LETTER E WITH CARON	GF-latin-plus	0
fhook	0x0192	ƒ	LATIN SMALL LETTER F WITH HOOK	GF-latin-plus	0
gcircumflex	0x011D	ĝ	LATIN SMALL LETTER G WITH CIRCUMFLEX	GF-latin-plus	0
gbreve	0x011F	ğ	LATIN SMALL LETTER G WITH BREVE	GF-latin-plus	0
gdotaccent	0x0121	ġ	LATIN SMALL LETTER G WITH DOT ABOVE	GF-latin-plus	0
gcedilla	0x0123	ģ	LATIN SMALL LETTER G WITH CEDILLA	GF-latin-plus	0
gcaron	0x01E7	ǧ	LATIN SMALL LETTER G WITH CARON	GF-latin-plus	0
hcircumflex	0x0125	ĥ	LATIN SMALL LETTER H WITH CIRCUMFLEX	GF-latin-plus	0
hbar	0x0127	ħ	LATIN SMALL LETTER H WITH STROKE	GF-latin-plus	0
dotlessi	0x0131	ı	LATIN SMALL LETTER DOTLESS I	GF-latin-core	0
igrave	0x00EC	ì	LATIN SMALL LETTER I WITH GRAVE	GF-latin-core	0
iacute	0x00ED	í	LATIN SMALL LETTER I WITH ACUTE	GF-latin-core	0
icircumflex	0x00EE	î	LATIN SMALL LETTER I WITH CIRCUMFLEX	GF-latin-core	0
idieresis	0x00EF	ï	LATIN SMALL LETTER I WITH DIAERESIS	GF-latin-core	0
itilde	0x0129	ĩ	LATIN SMALL LETTER I WITH TILDE	GF-latin-plus	0
imacron	0x012B	ī	LATIN SMALL LETTER I WITH MACRON	GF-latin-plus	0
ibreve	0x012D	ĭ	LATIN SMALL LETTER I WITH BREVE	GF-latin-plus	0
iogonek	0x012F	į	LATIN SMALL LETTER I WITH OGONEK	GF-latin-plus	0
jcircumflex	0x0135	ĵ	LATIN SMALL LETTER J WITH CIRCUMFLEX	GF-latin-plus	0
kcedilla	0x0137	ķ	LATIN SMALL LETTER K WITH CEDILLA	GF-latin-plus	0
lacute	0x013A	ĺ	LATIN SMALL LETTER L WITH ACUTE	GF-latin-plus	0
lcedilla	0x013C	ļ	LATIN SMALL LETTER L WITH CEDILLA	GF-latin-plus	0
lcaron	0x013E	ľ	LATIN SMALL LETTER L WITH CARON	GF-latin-plus	0
ldot	0x0140	ŀ	LATIN SMALL LETTER L WITH MIDDLE DOT	GF-latin-plus	0
lslash	0x0142	ł	LATIN SMALL LETTER L WITH STROKE	GF-latin-plus	0
ntilde	0x00F1	ñ	LATIN SMALL LETTER N WITH TILDE	GF-latin-core	0
nacute	0x0144	ń	LATIN SMALL LETTER N WITH ACUTE	GF-latin-plus	0
ncedilla	0x0146	ņ	LATIN SMALL LETTER N WITH CEDILLA	GF-latin-plus	0
ncaron	0x0148	ň	LATIN SMALL LETTER N WITH CARON	GF-latin-plus	0
eng	0x014B	ŋ	LATIN SMALL LETTER ENG	GF-latin-plus	0
ograve	0x00F2	ò	LATIN SMALL LETTER O WITH GRAVE	GF-latin-core	0
oacute	0x00F3	ó	LATIN SMALL LETTER O WITH ACUTE	GF-latin-core	0
ocircumflex	0x00F4	ô	LATIN SMALL LETTER O WITH CIRCUMFLEX	GF-latin-core	0
otilde	0x00F5	õ	LATIN SMALL LETTER O WITH TILDE	GF-latin-core	0
odieresis	0x00F6	ö	LATIN SMALL LETTER O WITH DIAERESIS	GF-latin-core	0
oslash	0x00F8	ø	LATIN SMALL LETTER O WITH STROKE	GF-latin-core	0
omacron	0x014D	ō	LATIN SMALL LETTER O WITH MACRON	GF-latin-plus	0
obreve	0x014F	ŏ	LATIN SMALL LETTER O WITH BREVE	GF-latin-plus	0
ohungarumlaut	0x0151	ő	LATIN SMALL LETTER O WITH DOUBLE ACUTE	GF-latin-plus	0
ohorn	0x01A1	ơ	LATIN SMALL LETTER O WITH HORN	GF-latin-plus	0
oogonek	0x01EB	ǫ	LATIN SMALL LETTER O WITH OGONEK	GF-latin-plus	0
oe	0x0153	œ	LATIN SMALL LIGATURE OE	GF-latin-core	0
thorn	0x00FE	þ	LATIN SMALL LETTER THORN	GF-latin-core	0
racute	0x0155	ŕ	LATIN SMALL LETTER R WITH ACUTE	GF-latin-plus	0
rcedilla	0x0157	ŗ	LATIN SMALL LETTER R WITH CEDILLA	GF-latin-plus	0
rcaron	0x0159	ř	LATIN SMALL LETTER R WITH CARON	GF-latin-plus	0
sacute	0x015B	ś	LATIN SMALL LETTER S WITH ACUTE	GF-latin-plus	0
scircumflex	0x015D	ŝ	LATIN SMALL LETTER S WITH CIRCUMFLEX	GF-latin-plus	0
scedilla	0x015F	ş	LATIN SMALL LETTER S WITH CEDILLA	GF-latin-plus	0
scaron	0x0161	š	LATIN SMALL LETTER S WITH CARON	GF-latin-plus	0
tcedilla	0x0163	ţ	LATIN SMALL LETTER T WITH CEDILLA	GF-latin-plus	0
tcaron	0x0165	ť	LATIN SMALL LETTER T WITH CARON	GF-latin-plus	0
tbar	0x0167	ŧ	LATIN SMALL LETTER T WITH STROKE	GF-latin-plus	0
ugrave	0x00F9	ù	LATIN SMALL LETTER U WITH GRAVE	GF-latin-core	0
uacute	0x00FA	ú	LATIN SMALL LETTER U WITH ACUTE	GF-latin-core	0
ucircumflex	0x00FB	û	LATIN SMALL LETTER U WITH CIRCUMFLEX	GF-latin-core	0
udieresis	0x00FC	ü	LATIN SMALL LETTER U WITH DIAERESIS	GF-latin-core	0
utilde	0x0169	ũ	LATIN SMALL LETTER U WITH TILDE	GF-latin-plus	0
umacron	0x016B	ū	LATIN SMALL LETTER U WITH MACRON	GF-latin-plus	0
ubreve	0x016D	ŭ	LATIN SMALL LETTER U WITH BREVE	GF-latin-plus	0
uring	0x016F	ů	LATIN SMALL LETTER U WITH RING ABOVE	GF-latin-plus	0
uhungarumlaut	0x0171	ű	LATIN SMALL LETTER U WITH DOUBLE ACUTE	GF-latin-plus	0
uogonek	0x0173	ų	LATIN SMALL LETTER U WITH OGONEK	GF-latin-plus	0
uhorn	0x01B0	ư	LATIN SMALL LETTER U WITH HORN	GF-latin-plus	0
wcircumflex	0x0175	ŵ	LATIN SMALL LETTER W WITH CIRCUMFLEX	GF-latin-plus	0
yacute	0x00FD	ý	LATIN SMALL LETTER Y WITH ACUTE	GF-latin-core	0
ycircumflex	0x0177	ŷ	LATIN SMALL LETTER Y WITH CIRCUMFLEX	GF-latin-plus	0
ydieresis	0x00FF	ÿ	LATIN SMALL LETTER Y WITH DIAERESIS	GF-latin-core	0
zacute	0x017A	ź	LATIN SMALL LETTER Z WITH ACUTE	GF-latin-plus	0
zdotaccent	0x017C	ż	LATIN SMALL LETTER Z WITH DOT ABOVE	GF-latin-plus	0
zcaron	0x017E	ž	LATIN SMALL LETTER Z WITH CARON	GF-latin-plus	0
Jcircumflex	0x0134	Ĵ	LATIN CAPITAL LETTER J WITH CIRCUMFLEX	GF-latin-plus	0
Kcedilla	0x0136	Ķ	LATIN CAPITAL LETTER K WITH CEDILLA	GF-latin-plus	0
kra	0x0138	ĸ	LATIN SMALL LETTER KRA	GF-latin-plus	0
Gcaron	0x01E6	Ǧ	LATIN CAPITAL LETTER G WITH CARON	GF-latin-plus	0
DZcaron	0x01C4	Ǆ	LATIN CAPITAL LETTER DZ WITH CARON	GF-latin-plus	0
Dzcaron	0x01C5	ǅ	LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON	GF-latin-plus	0
dzcaron	0x01C6	ǆ	LATIN SMALL LETTER DZ WITH CARON	GF-latin-plus	0
LJ	0x01C7	Ǉ	LATIN CAPITAL LETTER LJ	GF-latin-plus	0
Lj	0x01C8	ǈ	LATIN CAPITAL LETTER L WITH SMALL LETTER J	GF-latin-plus	0
lj	0x01C9	ǉ	LATIN SMALL LETTER LJ	GF-latin-plus	0
NJ	0x01CA	Ǌ	LATIN CAPITAL LETTER NJ	GF-latin-plus	0
Nj	0x01CB	ǋ	LATIN CAPITAL LETTER N WITH SMALL LETTER J	GF-latin-plus	0
nj	0x01CC	ǌ	LATIN SMALL LETTER NJ	GF-latin-plus	0
oslashacute	0x01FF	ǿ	LATIN SMALL LETTER O WITH STROKE AND ACUTE	GF-latin-plus	0
agravedbl	0x0201	ȁ	LATIN SMALL LETTER A WITH DOUBLE GRAVE	GF-latin-plus	0
ainvertedbreve	0x0203	ȃ	LATIN SMALL LETTER A WITH INVERTED BREVE	GF-latin-plus	0
egravedbl	0x0205	ȅ	LATIN SMALL LETTER E WITH DOUBLE GRAVE	GF-latin-plus	0
einvertedbreve	0x0207	ȇ	LATIN SMALL LETTER E WITH INVERTED BREVE	GF-latin-plus	0
igravedbl	0x0209	ȉ	LATIN SMALL LETTER I WITH DOUBLE GRAVE	GF-latin-plus	0
iinvertedbreve	0x020B	ȋ	LATIN SMALL LETTER I WITH INVERTED BREVE	GF-latin-plus	0
ogravedbl	0x020D	ȍ	LATIN SMALL LETTER O WITH DOUBLE GRAVE	GF-latin-plus	0
oinvertedbreve	0x020F	ȏ	LATIN SMALL LETTER O WITH INVERTED BREVE	GF-latin-plus	0
rgravedbl	0x0211	ȑ	LATIN SMALL LETTER R WITH DOUBLE GRAVE	GF-latin-plus	0
rinvertedbreve	0x0213	ȓ	LATIN SMALL LETTER R WITH INVERTED BREVE	GF-latin-plus	0
ugravedbl	0x0215	ȕ	LATIN SMALL LETTER U WITH DOUBLE GRAVE	GF-latin-plus	0
uinvertedbreve	0x0217	ȗ	LATIN SMALL LETTER U WITH INVERTED BREVE	GF-latin-plus	0
scommaaccent	0x0219	ș	LATIN SMALL LETTER S WITH COMMA BELOW	GF-latin-plus	0
tcommaaccent	0x021B	ț	LATIN SMALL LETTER T WITH COMMA BELOW	GF-latin-plus	0
odieresismacron	0x022B	ȫ	LATIN SMALL LETTER O WITH DIAERESIS AND MACRON	GF-latin-plus	0
otildemacron	0x022D	ȭ	LATIN SMALL LETTER O WITH TILDE AND MACRON	GF-latin-plus	0
odotmacron	0x0231	ȱ	LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON	GF-latin-plus	0
ymacron	0x0233	ȳ	LATIN SMALL LETTER Y WITH MACRON	GF-latin-plus	0
Wgrave	0x1E80	Ẁ	LATIN CAPITAL LETTER W WITH GRAVE	GF-latin-plus	0
wgrave	0x1E81	ẁ	LATIN SMALL LETTER W WITH GRAVE	GF-latin-plus	0
Wacute	0x1E82	Ẃ	LATIN CAPITAL LETTER W WITH ACUTE	GF-latin-plus	0
wacute	0x1E83	ẃ	LATIN SMALL LETTER W WITH ACUTE	GF-latin-plus	0
Wdieresis	0x1E84	Ẅ	LATIN CAPITAL LETTER W WITH DIAERESIS	GF-latin-plus	0
wdieresis	0x1E85	ẅ	LATIN SMALL LETTER W WITH DIAERESIS	GF-latin-plus	0
Germandbls	0x1E9E	ẞ	LATIN CAPITAL LETTER SHARP S	GF-latin-plus	0
Adotbelow	0x1EA0	Ạ	LATIN CAPITAL LETTER A WITH DOT BELOW	GF-latin-plus	0
adotbelow	0x1EA1	ạ	LATIN SMALL LETTER A WITH DOT BELOW	GF-latin-plus	0
Ahoi	0x1EA2	Ả	LATIN CAPITAL LETTER A WITH HOOK ABOVE	GF-latin-plus	0
ahoi	0x1EA3	ả	LATIN SMALL LETTER A WITH HOOK ABOVE	GF-latin-plus	0
Acircumflexacute	0x1EA4	Ấ	LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE	GF-latin-plus	0
acircumflexacute	0x1EA5	ấ	LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE	GF-latin-plus	0
Acircumflexgrave	0x1EA6	Ầ	LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE	GF-latin-plus	0
acircumflexgrave	0x1EA7	ầ	LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE	GF-latin-plus	0
Acircumflexhoi	0x1EA8	Ẩ	LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE	GF-latin-plus	0
acircumflexhoi	0x1EA9	ẩ	LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE	GF-latin-plus	0
Acircumflextilde	0x1EAA	Ẫ	LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE	GF-latin-plus	0
acircumflextilde	0x1EAB	ẫ	LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE	GF-latin-plus	0
Acircumflexdotbelow	0x1EAC	Ậ	LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW	GF-latin-plus	0
acircumflexdotbelow	0x1EAD	ậ	LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW	GF-latin-plus	0
Abreveacute	0x1EAE	Ắ	LATIN CAPITAL LETTER A WITH BREVE AND ACUTE	GF-latin-plus	0
abreveacute	0x1EAF	ắ	LATIN SMALL LETTER A WITH BREVE AND ACUTE	GF-latin-plus	0
Abrevegrave	0x1EB0	Ằ	LATIN CAPITAL LETTER A WITH BREVE AND GRAVE	GF-latin-plus	0
abrevegrave	0x1EB1	ằ	LATIN SMALL LETTER A WITH BREVE AND GRAVE	GF-latin-plus	0
Abrevehoi	0x1EB2	Ẳ	LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE	GF-latin-plus	0
abrevehoi	0x1EB3	ẳ	LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE	GF-latin-plus	0
Abrevetilde	0x1EB4	Ẵ	LATIN CAPITAL LETTER A WITH BREVE AND TILDE	GF-latin-plus	0
abrevetilde	0x1EB5	ẵ	LATIN SMALL LETTER A WITH BREVE AND TILDE	GF-latin-plus	0
Abrevedotbelow	0x1EB6	Ặ	LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW	GF-latin-plus	0
abrevedotbelow	0x1EB7	ặ	LATIN SMALL LETTER A WITH BREVE AND DOT BELOW	GF-latin-plus	0
Edotbelow	0x1EB8	Ẹ	LATIN CAPITAL LETTER E WITH DOT BELOW	GF-latin-plus	0
edotbelow	0x1EB9	ẹ	LATIN SMALL LETTER E WITH DOT BELOW	GF-latin-plus	0
Ehoi	0x1EBA	Ẻ	LATIN CAPITAL LETTER E WITH HOOK ABOVE	GF-latin-plus	0
ehoi	0x1EBB	ẻ	LATIN SMALL LETTER E WITH HOOK ABOVE	GF-latin-plus	0
Etilde	0x1EBC	Ẽ	LATIN CAPITAL LETTER E WITH TILDE	GF-latin-plus	0
etilde	0x1EBD	ẽ	LATIN SMALL LETTER E WITH TILDE	GF-latin-plus	0
Ecircumflexacute	0x1EBE	Ế	LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE	GF-latin-plus	0
ecircumflexacute	0x1EBF	ế	LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE	GF-latin-plus	0
Ecircumflexgrave	0x1EC0	Ề	LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE	GF-latin-plus	0
ecircumflexgrave	0x1EC1	ề	LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE	GF-latin-plus	0
Ecircumflexhoi	0x1EC2	Ể	LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE	GF-latin-plus	0
ecircumflexhoi	0x1EC3	ể	LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE	GF-latin-plus	0
Ecircumflextilde	0x1EC4	Ễ	LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE	GF-latin-plus	0
ecircumflextilde	0x1EC5	ễ	LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE	GF-latin-plus	0
Ecircumflexdotbelow	0x1EC6	Ệ	LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW	GF-latin-plus	0
ecircumflexdotbelow	0x1EC7	ệ	LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW	GF-latin-plus	0
Ihoi	0x1EC8	Ỉ	LATIN CAPITAL LETTER I WITH HOOK ABOVE	GF-latin-plus	0
ihoi	0x1EC9	ỉ	LATIN SMALL LETTER I WITH HOOK ABOVE	GF-latin-plus	0
Idotbelow	0x1ECA	Ị	LATIN CAPITAL LETTER I WITH DOT BELOW	GF-latin-plus	0
idotbelow	0x1ECB	ị	LATIN SMALL LETTER I WITH DOT BELOW	GF-latin-plus	0
Odotbelow	0x1ECC	Ọ	LATIN CAPITAL LETTER O WITH DOT BELOW	GF-latin-plus	0
odotbelow	0x1ECD	ọ	LATIN SMALL LETTER O WITH DOT BELOW	GF-latin-plus	0
Ohoi	0x1ECE	Ỏ	LATIN CAPITAL LETTER O WITH HOOK ABOVE	GF-latin-plus	0
ohoi	0x1ECF	ỏ	LATIN SMALL LETTER O WITH HOOK ABOVE	GF-latin-plus	0
Ocircumflexacute	0x1ED0	Ố	LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE	GF-latin-plus	0
ocircumflexacute	0x1ED1	ố	LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE	GF-latin-plus	0
Ocircumflexgrave	0x1ED2	Ồ	LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE	GF-latin-plus	0
ocircumflexgrave	0x1ED3	ồ	LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE	GF-latin-plus	0
Ocircumflexhoi	0x1ED4	Ổ	LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE	GF-latin-plus	0
ocircumflexhoi	0x1ED5	ổ	LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE	GF-latin-plus	0
Ocircumflextilde	0x1ED6	Ỗ	LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE	GF-latin-plus	0
ocircumflextilde	0x1ED7	ỗ	LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE	GF-latin-plus	0
Ocircumflexdotbelow	0x1ED8	Ộ	LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW	GF-latin-plus	0
ocircumflexdotbelow	0x1ED9	ộ	LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW	GF-latin-plus	0
Ohornacute	0x1EDA	Ớ	LATIN CAPITAL LETTER O WITH HORN AND ACUTE	GF-latin-plus	0
ohornacute	0x1EDB	ớ	LATIN SMALL LETTER O WITH HORN AND ACUTE	GF-latin-plus	0
Ohorngrave	0x1EDC	Ờ	LATIN CAPITAL LETTER O WITH HORN AND GRAVE	GF-latin-plus	0
ohorngrave	0x1EDD	ờ	LATIN SMALL LETTER O WITH HORN AND GRAVE	GF-latin-plus	0
Ohornhoi	0x1EDE	Ở	LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE	GF-latin-plus	0
ohornhoi	0x1EDF	ở	LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE	GF-latin-plus	0
Ohorntilde	0x1EE0	Ỡ	LATIN CAPITAL LETTER O WITH HORN AND TILDE	GF-latin-plus	0
ohorntilde	0x1EE1	ỡ	LATIN SMALL LETTER O WITH HORN AND TILDE	GF-latin-plus	0
Ohorndotbelow	0x1EE2	Ợ	LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW	GF-latin-plus	0
ohorndotbelow	0x1EE3	ợ	LATIN SMALL LETTER O WITH HORN AND DOT BELOW	GF-latin-plus	0
Udotbelow	0x1EE4	Ụ	LATIN CAPITAL LETTER U WITH DOT BELOW	GF-latin-plus	0
udotbelow	0x1EE5	ụ	LATIN SMALL LETTER U WITH DOT BELOW	GF-latin-plus	0
Uhoi	0x1EE6	Ủ	LATIN CAPITAL LETTER U WITH HOOK ABOVE	GF-latin-plus	0
uhoi	0x1EE7	ủ	LATIN SMALL LETTER U WITH HOOK ABOVE	GF-latin-plus	0
Uhornacute	0x1EE8	Ứ	LATIN CAPITAL LETTER U WITH HORN AND ACUTE	GF-latin-plus	0
uhornacute	0x1EE9	ứ	LATIN SMALL LETTER U WITH HORN AND ACUTE	GF-latin-plus	0
Uhorngrave	0x1EEA	Ừ	LATIN CAPITAL LETTER U WITH HORN AND GRAVE	GF-latin-plus	0
uhorngrave	0x1EEB	ừ	LATIN SMALL LETTER U WITH HORN AND GRAVE	GF-latin-plus	0
Uhornhoi	0x1EEC	Ử	LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE	GF-latin-plus	0
uhornhoi	0x1EED	ử	LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE	GF-latin-plus	0
Uhorntilde	0x1EEE	Ữ	LATIN CAPITAL LETTER U WITH HORN AND TILDE	GF-latin-plus	0
uhorntilde	0x1EEF	ữ	LATIN SMALL LETTER U WITH HORN AND TILDE	GF-latin-plus	0
Uhorndotbelow	0x1EF0	Ự	LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW	GF-latin-plus	0
uhorndotbelow	0x1EF1	ự	LATIN SMALL LETTER U WITH HORN AND DOT BELOW	GF-latin-plus	0
Ygrave	0x1EF2	Ỳ	LATIN CAPITAL LETTER Y WITH GRAVE	GF-latin-plus	0
ygrave	0x1EF3	ỳ	LATIN SMALL LETTER Y WITH GRAVE	GF-latin-plus	0
Ydotbelow	0x1EF4	Ỵ	LATIN CAPITAL LETTER Y WITH DOT BELOW	GF-latin-plus	0
ydotbelow	0x1EF5	ỵ	LATIN SMALL LETTER Y WITH DOT BELOW	GF-latin-plus	0
Yhoi	0x1EF6	Ỷ	LATIN CAPITAL LETTER Y WITH HOOK ABOVE	GF-latin-plus	0
yhoi	0x1EF7	ỷ	LATIN SMALL LETTER Y WITH HOOK ABOVE	GF-latin-plus	0
Ytilde	0x1EF8	Ỹ	LATIN CAPITAL LETTER Y WITH TILDE	GF-latin-plus	0
ytilde	0x1EF9	ỹ	LATIN SMALL LETTER Y WITH TILDE	GF-latin-plus	0
Ccedillaacute	0x1E08	Ḉ	LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE	GF-latin-pro	0
ccedillaacute	0x1E09	ḉ	LATIN SMALL LETTER C WITH CEDILLA AND ACUTE	GF-latin-pro	0
Ddotbelow	0x1E0C	Ḍ	LATIN CAPITAL LETTER D WITH DOT BELOW	GF-latin-pro	0
ddotbelow	0x1E0D	ḍ	LATIN SMALL LETTER D WITH DOT BELOW	GF-latin-pro	0
Dlinebelow	0x1E0E	Ḏ	LATIN CAPITAL LETTER D WITH LINE BELOW	GF-latin-pro	0
dlinebelow	0x1E0F	ḏ	LATIN SMALL LETTER D WITH LINE BELOW	GF-latin-pro	0
Emacrongrave	0x1E14	Ḕ	LATIN CAPITAL LETTER E WITH MACRON AND GRAVE	GF-latin-pro	0
emacrongrave	0x1E15	ḕ	LATIN SMALL LETTER E WITH MACRON AND GRAVE	GF-latin-pro	0
Emacronacute	0x1E16	Ḗ	LATIN CAPITAL LETTER E WITH MACRON AND ACUTE	GF-latin-pro	0
emacronacute	0x1E17	ḗ	LATIN SMALL LETTER E WITH MACRON AND ACUTE	GF-latin-pro	0
Ecedillabreve	0x1E1C	Ḝ	LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE	GF-latin-pro	0
ecedillabreve	0x1E1D	ḝ	LATIN SMALL LETTER E WITH CEDILLA AND BREVE	GF-latin-pro	0
Gmacron	0x1E20	Ḡ	LATIN CAPITAL LETTER G WITH MACRON	GF-latin-pro	0
gmacron	0x1E21	ḡ	LATIN SMALL LETTER G WITH MACRON	GF-latin-pro	0
Hdotbelow	0x1E24	Ḥ	LATIN CAPITAL LETTER H WITH DOT BELOW	GF-latin-pro	0
hdotbelow	0x1E25	ḥ	LATIN SMALL LETTER H WITH DOT BELOW	GF-latin-pro	0
Hbrevebelow	0x1E2A	Ḫ	LATIN CAPITAL LETTER H WITH BREVE BELOW	GF-latin-pro	0
hbrevebelow	0x1E2B	ḫ	LATIN SMALL LETTER H WITH BREVE BELOW	GF-latin-pro	0
Idieresisacute	0x1E2E	Ḯ	LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE	GF-latin-pro	0
idieresisacute	0x1E2F	ḯ	LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE	GF-latin-pro	0
Ldotbelow	0x1E36	Ḷ	LATIN CAPITAL LETTER L WITH DOT BELOW	GF-latin-pro	0
ldotbelow	0x1E37	ḷ	LATIN SMALL LETTER L WITH DOT BELOW	GF-latin-pro	0
Llinebelow	0x1E3A	Ḻ	LATIN CAPITAL LETTER L WITH LINE BELOW	GF-latin-pro	0
llinebelow	0x1E3B	ḻ	LATIN SMALL LETTER L WITH LINE BELOW	GF-latin-pro	0
Mdotbelow	0x1E42	Ṃ	LATIN CAPITAL LETTER M WITH DOT BELOW	GF-latin-pro	0
mdotbelow	0x1E43	ṃ	LATIN SMALL LETTER M WITH DOT BELOW	GF-latin-pro	0
Ndot	0x1E44	Ṅ	LATIN CAPITAL LETTER N WITH DOT ABOVE	GF-latin-pro	0
ndot	0x1E45	ṅ	LATIN SMALL LETTER N WITH DOT ABOVE	GF-latin-pro	0
Ndotbelow	0x1E46	Ṇ	LATIN CAPITAL LETTER N WITH DOT BELOW	GF-latin-pro	0
ndotbelow	0x1E47	ṇ	LATIN SMALL LETTER N WITH DOT BELOW	GF-latin-pro	0
Nlinebelow	0x1E48	Ṉ	LATIN CAPITAL LETTER N WITH LINE BELOW	GF-latin-pro	0
nlinebelow	0x1E49	ṉ	LATIN SMALL LETTER N WITH LINE BELOW	GF-latin-pro	0
Otildeacute	0x1E4C	Ṍ	LATIN CAPITAL LETTER O WITH TILDE AND ACUTE	GF-latin-pro	0
otildeacute	0x1E4D	ṍ	LATIN SMALL LETTER O WITH TILDE AND ACUTE	GF-latin-pro	0
Otildedieresis	0x1E4E	Ṏ	LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS	GF-latin-pro	0
otildedieresis	0x1E4F	ṏ	LATIN SMALL LETTER O WITH TILDE AND DIAERESIS	GF-latin-pro	0
Omacrongrave	0x1E50	Ṑ	LATIN CAPITAL LETTER O WITH MACRON AND GRAVE	GF-latin-pro	0
omacrongrave	0x1E51	ṑ	LATIN SMALL LETTER O WITH MACRON AND GRAVE	GF-latin-pro	0
Omacronacute	0x1E52	Ṓ	LATIN CAPITAL LETTER O WITH MACRON AND ACUTE	GF-latin-pro	0
omacronacute	0x1E53	ṓ	LATIN SMALL LETTER O WITH MACRON AND ACUTE	GF-latin-pro	0
Rdotbelow	0x1E5A	Ṛ	LATIN CAPITAL LETTER R WITH DOT BELOW	GF-latin-pro	0
rdotbelow	0x1E5B	ṛ	LATIN SMALL LETTER R WITH DOT BELOW	GF-latin-pro	0
Rlinebelow	0x1E5E	Ṟ	LATIN CAPITAL LETTER R WITH LINE BELOW	GF-latin-pro	0
rlinebelow	0x1E5F	ṟ	LATIN SMALL LETTER R WITH LINE BELOW	GF-latin-pro	0
Sdot	0x1E60	Ṡ	LATIN CAPITAL LETTER S WITH DOT ABOVE	GF-latin-pro	0
sdot	0x1E61	ṡ	LATIN SMALL LETTER S WITH DOT ABOVE	GF-latin-pro	0
Sdotbelow	0x1E62	Ṣ	LATIN CAPITAL LETTER S WITH DOT BELOW	GF-latin-pro	0
sdotbelow	0x1E63	ṣ	LATIN SMALL LETTER S WITH DOT BELOW	GF-latin-pro	0
Sacutedotaccent	0x1E64	Ṥ	LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE	GF-latin-pro	0
sacutedotaccent	0x1E65	ṥ	LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE	GF-latin-pro	0
Scarondot	0x1E66	Ṧ	LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE	GF-latin-pro	0
scarondot	0x1E67	ṧ	LATIN SMALL LETTER S WITH CARON AND DOT ABOVE	GF-latin-pro	0
Sdotbelowdotabove	0x1E68	Ṩ	LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE	GF-latin-pro	0
sdotbelowdotabove	0x1E69	ṩ	LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE	GF-latin-pro	0
Tdotbelow	0x1E6C	Ṭ	LATIN CAPITAL LETTER T WITH DOT BELOW	GF-latin-pro	0
tdotbelow	0x1E6D	ṭ	LATIN SMALL LETTER T WITH DOT BELOW	GF-latin-pro	0
Tlinebelow	0x1E6E	Ṯ	LATIN CAPITAL LETTER T WITH LINE BELOW	GF-latin-pro	0
tlinebelow	0x1E6F	ṯ	LATIN SMALL LETTER T WITH LINE BELOW	GF-latin-pro	0
Utildeacute	0x1E78	Ṹ	LATIN CAPITAL LETTER U WITH TILDE AND ACUTE	GF-latin-pro	0
utildeacute	0x1E79	ṹ	LATIN SMALL LETTER U WITH TILDE AND ACUTE	GF-latin-pro	0
Umacrondieresis	0x1E7A	Ṻ	LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS	GF-latin-pro	0
umacrondieresis	0x1E7B	ṻ	LATIN SMALL LETTER U WITH MACRON AND DIAERESIS	GF-latin-pro	0
Ydot	0x1E8E	Ẏ	LATIN CAPITAL LETTER Y WITH DOT ABOVE	GF-latin-pro	0
ydot	0x1E8F	ẏ	LATIN SMALL LETTER Y WITH DOT ABOVE	GF-latin-pro	0
Zdotbelow	0x1E92	Ẓ	LATIN CAPITAL LETTER Z WITH DOT BELOW	GF-latin-pro	0
zdotbelow	0x1E93	ẓ	LATIN SMALL LETTER Z WITH DOT BELOW	GF-latin-pro	0
tdieresis	0x1E97	ẗ	LATIN SMALL LETTER T WITH DIAERESIS	GF-latin-pro	0
dotlessj	0x0237	ȷ	LATIN SMALL LETTER DOTLESS J	GF-latin-plus	0
schwa	0x0259	ə	LATIN SMALL LETTER SCHWA	GF-latin-plus	0"""



# Categories the parts of the description
allCases = ["UC", "LC", "OTHER"]
allBaseGlyphs = []
allAccents = []


allChars = allChars.split("\n")
#print(len(allChars))
allCharsWithAttrs = []
for c in allChars:
    cSplit = c.split("\t")
    
    description = cSplit[3]
    
    if "LATIN CAPITAL" in description:
        case = "UC"
    elif "LATIN SMALL" in description:
        case = "LC"
    else: case = "OTHER"
    
    baseGlyph = ""
    accent = ""
    if "LETTER" in description:
        if not "WITH" in description:
            baseGlyph = description.split("LETTER ")[1]
            if " " in baseGlyph:
                baseGlyph = baseGlyph.split(" ")[1]
        else:
            baseGlyph = description.split("LETTER ")[1].split(" ")[0]
            accent = description.split("WITH ")[1]

    if not baseGlyph in allBaseGlyphs:
        allBaseGlyphs.append(baseGlyph)
    if not accent in allAccents:
        allAccents.append(accent)
    
    sortAttrs = (case, baseGlyph, accent)
    allCharsWithAttrs.append([sortAttrs, c])

# Sort the attrs and then sort the allCharsWithAttrs
allBaseGlyphs.sort()
allAccents.sort()

# Turn the sorting attributes into indices
for cIdx, c in enumerate(allCharsWithAttrs):
    attrs, charInfo = c
    attrs = (allCases.index(attrs[0]),
        allBaseGlyphs.index(attrs[1]),
        allAccents.index(attrs[2]))
    allCharsWithAttrs[cIdx] = (attrs, charInfo)


# Sort the allGlyphs
allCharsWithAttrs = sorted(allCharsWithAttrs, key = lambda x: (x[0][0], x[0][1], x[0][2]))

for c in allCharsWithAttrs:
    print(c[1])
